name: 01-Building

on: 
  workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run : echo "hello world"
            - name: you okay
              run : echo "You Okay?"