name: 06 - Contexts
run-name: DEBUG - ${{inputs.debug}}

on: 
  push:
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false


env:
  hello: Sundareswar


jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: | 
                echo "Event name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Run number: ${{github.run_number}}"
            - name: Disp
              run: |
                echo "Variable value: ${{env.hello}}"
            - name: New
              env:
                hello: Great
              run: echo ${{env.hello}}
              