name: 07 - Using Expressions
run-name: if ${{inputs.debug}} && ON || OFF

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                default: false
                type: boolean

jobs:
    Hello:
        runs-on: ubuntu-latest
        steps:
            - name: xxx
              if: ${{inputs.debug}}
              run: |
               echo "Hello"